### ISSUE TITLE
DPL-599 Prepare for upgrade Postgresql 14 [Time Sensitive - 1/2/23]

### ISSUE THREAD

**Issue by emrojo** [sanger/baracoda#323]
**Describe the Housekeeping**
Systems are asking for upgrade postgresql database. This will require testing baracoda and check that code is compatible and performance doesnt decrease. 
We are aiming to have this tests done by the end of january so they can perform the upgrade.

**Blocking issues**
Describe any other issues or tickets that may be blocking this change.

**Additional context**

**Comment by emrojo** [comment]
**Tasks**
- [ ] Check that all endpoints work as expected
- [ ] Compare performance with previous version 
- [ ] Run the integration suite and check that all is ok
- [ ] Plan how we are going to do the downtime for the upgrade
